apiVersion: kubeadm.k8s.io/v1beta3
kind: JoinConfiguration
nodeRegistration:
  name: uor-node
  taints: []
  kubeletExtraArgs:
    enable-controller-attach-detach: "false"
    node-labels: "uor-node=demo"
    node-ip: $NEBULAIP
    resolv-conf: /etc/resolv.conf
discovery:
  bootstrapToken:
    apiServerEndpoint: 
    token: 
    caCertHashes:
    - 
---
apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
kubernetesVersion: stable
controlPlaneEndpoint: 
